In [8]:
# Universal Functions in Array 

In [12]:
import numpy as np

In [13]:
salaries =np.genfomtxt('salary.csv',delimiter=',')

AttributeError: module 'numpy' has no attribute 'genfomtxt'

In [14]:
salaries

NameError: name 'salaries' is not defined

In [18]:
salaries.shape

NameError: name 'salaries' is not defined

In [ ]:
#wanted to apply statistical operations on top of the file

In [17]:
mean =np.mean(salaries)
median =np.median(salaries)
sd=np.std(salaries)
variance =np.var(salaries)

NameError: name 'salaries' is not defined

In [16]:
print('Mean =%i'%mean)
print('Median =%i'%median)
print('standard Deviation =%i'%sd)
print('Variance'%variance)


NameError: name 'mean' is not defined

In [20]:
# indexing and slicing of arrays

a =np.arange(11)**2




In [21]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [22]:
a[2]




4

In [ ]:
# slicing in array
# break the array into differnt groups

In [23]:
a[0:2]

array([0, 1], dtype=int32)

In [24]:
a[3:6]

array([ 9, 16, 25], dtype=int32)

In [25]:
# how do you print reverse of the array 
a[::-1] # it will take negative type of array

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [28]:
students =np.array([['pradip','yuvaanshi','scarlett','chrissy'],
                  [45,55,70,80],
                  [30,45,50,65]])


In [29]:
print(students)

[['pradip' 'yuvaanshi' 'scarlett' 'chrissy']
 ['45' '55' '70' '80']
 ['30' '45' '50' '65']]


In [31]:
students[0]

array(['pradip', 'yuvaanshi', 'scarlett', 'chrissy'], dtype='<U9')

In [32]:
students[1]  

array(['45', '55', '70', '80'], dtype='<U9')

In [ ]:
# u --> unicode
# < --> little indian style format
# > --> big indian style format


In [34]:
students[2]

array(['30', '45', '50', '65'], dtype='<U9')

In [ ]:
req is to retrive yuvaanshi name from the output

In [35]:
students[0,1]  # consider 0, 1 as x,y --x--> is defined for the row, 0

'yuvaanshi'

In [36]:
students[0,3]

'chrissy'