In [1]:
import numpy as np

In [4]:
array_of_zeros=np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
array_of_ones=np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# req is to eliminate the dots after ones/zeros in array
array_of_ones_int =np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [15]:
array_empty = np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# int16,  --> upto thousand or ten thousands
# int32--> upto billion
# int64

In [14]:
array_eye =np.eye(4)
array_eye  # to print identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
req is to print even numbers from 1 to 20

In [17]:
list(range(2,20,2))

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [21]:
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
array_of_floats = np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
understanding 2-dimensional arrays


In [27]:
array_2d =np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [30]:
array_2d.shape # how to know which type of matrix

(2, 3)

In [31]:
np.arange(6)  # instantly creating an array

array([0, 1, 2, 3, 4, 5])

In [32]:
array_nd=np.arange(6).reshape(3,2)  # trying to change he matrix by using reshape 
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
array_nd=np.arange(6).reshape(4,1)  # whenever we using the reshape the rows and columns are giving the arange number 
array_nd   

ValueError: cannot reshape array of size 6 into shape (4,1)

In [35]:
array_nd=np.arange(8).reshape(2,4)  # trying to change he matrix by using reshape 
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
difference b/w printing and calling

In [38]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]
